name: spring_boot_unoptimized

services:
  spring_boot_unoptimized:
    image: mysql:9.0.1
    command: --lower_case_table_names=0
    restart: always
    ports:
      - "2108:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: spring_boot_unoptimized
      TZ: Europe/Berlin